# https://projecteuler.net/problem=2
# Even Fibonacci numbers

# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def get_sum_of_even_valued_fibonacci_terms_below_limit(limit):
    a = 1
    b = 2
    summa = 0
    try:
        while (a < limit):
            if a % 2 == 0:
                summa += a
            temp = a
            a = b
            b = temp + a
    except:
        print('Parameter limit must be a number!')

    finally:
        return summa
